use_sim_uav: false

use_sim_car: false

pub_hz_: 200

t_uav_per: 3.0

t_car_per: 5.0

car_R: 15.0

car_V: 0.8

car_P_x: [0.0,  3.0,  6.0,  8.0,  6.0,  3.0, 0.0, -3.0, -6.0, -8.0, -6.0, -3.0]

car_P_y: [0.0,  1.5,  3.0,  0.0, -3.0, -1.5, 0.0,  1.5,  3.0,  0.0, -3.0, -2.5]

car_P_z: [0.0, -0.5, -1.0, -1.0, -1.0, -0.5, 0.0,  0.5,  1.0,  1.0,  0.5,  0.0]

uav_P_x: [0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 8.0, 6.0, 4.0, 2.0]

uav_P_y: [0.0, 4.0, 4.9, 4.9, 4.0, 0.0, -4.0, -4.9, -4.9, 4.0]

uav_P_z: [4.0, 3.5, 3.0, 2.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.0]

time_delay: 0.03

trans_x: 3.0

trans_y: 2.0

trans_z: 0.0

rotat_roll: 0.0

rotat_pitch: 0.0

rotat_yaw: 0.2